import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
// import { StackProvider } from "@stackframe/stack"; // <-- 1. ADD THIS IMPORT

import { StackProvider, StackTheme } from "@stackframe/stack";
// import { stackServerApp } from "@/stack/server";

import { stack } from "@/stack";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StackProvider app={stack}> {/* <-- 2. WRAP YOUR CHILDREN */}
          <StackTheme>
            <Header />
          {children}
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}